CREATE TABLE USERS
(
    ID               INTEGER NOT NULL AUTO_INCREMENT,
    TELEGRAM_USER_ID INTEGER,
    USERNAME         VARCHAR(45),
    NICK_NAME        VARCHAR(45),
    PASSWORD         VARCHAR(60),
    PRIMARY KEY (ID)
);
